[workspace]
resolver = "2"

members = [
    "greeter",
    "guessing_game",
    "minigrep",
    "trait_tip_1",
    "st_webserver",
    "vec_ref_slice",
    "async-demo-1",
    "async-demo-2",
    "atomics_book_spin_lock",
]
